# Generated by Django 3.0.7 on 2020-07-20 01:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=80)),
                ('release_year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('movies_as_director', models.ManyToManyField(related_name='directors', through='catalog.DirectedBy', to='catalog.Movie')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StarringBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProducedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='movies_as_producer',
            field=models.ManyToManyField(related_name='producers', through='catalog.ProducedBy', to='catalog.Movie'),
        ),
        migrations.AddField(
            model_name='person',
            name='movies_played',
            field=models.ManyToManyField(related_name='casting', through='catalog.StarringBy', to='catalog.Movie'),
        ),
        migrations.AddField(
            model_name='directedby',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie'),
        ),
        migrations.AddField(
            model_name='directedby',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Person'),
        ),
        migrations.CreateModel(
            name='AlsoKnownAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Person')),
            ],
        ),
    ]
